// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import amazons3connector.AmazonHelper;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.sts.StsClient;
import software.amazon.awssdk.services.sts.model.GetCallerIdentityResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returns the account of the credentials.
 */
public class ValidateConnection extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __configuration;
	private amazons3connector.proxies.AwsConfig configuration;

	public ValidateConnection(IContext context, IMendixObject configuration)
	{
		super(context);
		this.__configuration = configuration;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.configuration = __configuration == null ? null : amazons3connector.proxies.AwsConfig.initialize(getContext(), __configuration);

		// BEGIN USER CODE
		StsClient client = AmazonHelper.GetStsClient(configuration);
		GetCallerIdentityResponse response = client.getCallerIdentity();
		return response.account();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ValidateConnection";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
