// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package huaweiobsconnector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the HuaweiOBSConnector module

	public static java.lang.String getDomainName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("HuaweiOBSConnector.DomainName");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("HuaweiOBSConnector.LogNode");
	}
}