// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazons3connector.proxies;

public class GetAsText
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject getAsTextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonS3Connector.GetAsText";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		GetAsText_Explorer("AmazonS3Connector.GetAsText_Explorer"),
		GetAsText_S3Object("AmazonS3Connector.GetAsText_S3Object");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GetAsText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AmazonS3Connector.GetAsText"));
	}

	protected GetAsText(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject getAsTextMendixObject)
	{
		if (getAsTextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AmazonS3Connector.GetAsText", getAsTextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AmazonS3Connector.GetAsText");

		this.getAsTextMendixObject = getAsTextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GetAsText.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amazons3connector.proxies.GetAsText initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amazons3connector.proxies.GetAsText.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amazons3connector.proxies.GetAsText initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazons3connector.proxies.GetAsText(context, mendixObject);
	}

	public static amazons3connector.proxies.GetAsText load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazons3connector.proxies.GetAsText.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of GetAsText_Explorer
	 */
	public final amazons3connector.proxies.Explorer getGetAsText_Explorer() throws com.mendix.core.CoreException
	{
		return getGetAsText_Explorer(getContext());
	}

	/**
	 * @param context
	 * @return value of GetAsText_Explorer
	 */
	public final amazons3connector.proxies.Explorer getGetAsText_Explorer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazons3connector.proxies.Explorer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GetAsText_Explorer.toString());
		if (identifier != null)
			result = amazons3connector.proxies.Explorer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GetAsText_Explorer
	 * @param getastext_explorer
	 */
	public final void setGetAsText_Explorer(amazons3connector.proxies.Explorer getastext_explorer)
	{
		setGetAsText_Explorer(getContext(), getastext_explorer);
	}

	/**
	 * Set value of GetAsText_Explorer
	 * @param context
	 * @param getastext_explorer
	 */
	public final void setGetAsText_Explorer(com.mendix.systemwideinterfaces.core.IContext context, amazons3connector.proxies.Explorer getastext_explorer)
	{
		if (getastext_explorer == null)
			getMendixObject().setValue(context, MemberNames.GetAsText_Explorer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GetAsText_Explorer.toString(), getastext_explorer.getMendixObject().getId());
	}

	/**
	 * @return value of GetAsText_S3Object
	 */
	public final amazons3connector.proxies.S3Object getGetAsText_S3Object() throws com.mendix.core.CoreException
	{
		return getGetAsText_S3Object(getContext());
	}

	/**
	 * @param context
	 * @return value of GetAsText_S3Object
	 */
	public final amazons3connector.proxies.S3Object getGetAsText_S3Object(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazons3connector.proxies.S3Object result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GetAsText_S3Object.toString());
		if (identifier != null)
			result = amazons3connector.proxies.S3Object.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GetAsText_S3Object
	 * @param getastext_s3object
	 */
	public final void setGetAsText_S3Object(amazons3connector.proxies.S3Object getastext_s3object)
	{
		setGetAsText_S3Object(getContext(), getastext_s3object);
	}

	/**
	 * Set value of GetAsText_S3Object
	 * @param context
	 * @param getastext_s3object
	 */
	public final void setGetAsText_S3Object(com.mendix.systemwideinterfaces.core.IContext context, amazons3connector.proxies.S3Object getastext_s3object)
	{
		if (getastext_s3object == null)
			getMendixObject().setValue(context, MemberNames.GetAsText_S3Object.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GetAsText_S3Object.toString(), getastext_s3object.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return getAsTextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazons3connector.proxies.GetAsText that = (amazons3connector.proxies.GetAsText) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AmazonS3Connector.GetAsText";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
