// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package huaweiobsconnector.actions;

import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.obs.services.ObsClient;
import com.obs.services.model.GetObjectRequest;
import huaweiobsconnector.HuaweiHelper;
import system.proxies.FileDocument;

public class GetObject extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __config;
	private huaweiobsconnector.proxies.HuaweiConfig config;
	private java.lang.String bucket;
	private java.lang.String key;
	private java.lang.String fileDocumentType;

	public GetObject(IContext context, IMendixObject config, java.lang.String bucket, java.lang.String key, java.lang.String fileDocumentType)
	{
		super(context);
		this.__config = config;
		this.bucket = bucket;
		this.key = key;
		this.fileDocumentType = fileDocumentType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.config = __config == null ? null : huaweiobsconnector.proxies.HuaweiConfig.initialize(getContext(), __config);

		// BEGIN USER CODE
		HuaweiHelper.printConfig(config);
		
		ObsClient client = HuaweiHelper.GetStsClient(config);
		if (!Core.isSubClassOf(FileDocument.entityName, fileDocumentType)) {
			throw new CoreException("Provided type is not of FileDocument!");
		}
		
		GetObjectRequest req = new GetObjectRequest(this.bucket, this.key);
		
		String fileName = key.substring(key.lastIndexOf('/') + 1);
		IMendixObject target = Core.instantiate(getContext(), fileDocumentType);
		InputStream is = client.getObject(req).getObjectContent();
		Core.storeFileDocumentContent(getContext(), target, fileName, is);
		
		return target;		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
