// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package huaweiobsconnector.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.obs.services.ObsClient;
import com.obs.services.model.ListBucketsRequest;
import com.obs.services.model.ObsBucket;
import huaweiobsconnector.HuaweiHelper;
import huaweiobsconnector.proxies.Bucket;

public class ListBuckets extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __config;
	private huaweiobsconnector.proxies.HuaweiConfig config;

	public ListBuckets(IContext context, IMendixObject config)
	{
		super(context);
		this.__config = config;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.config = __config == null ? null : huaweiobsconnector.proxies.HuaweiConfig.initialize(getContext(), __config);

		// BEGIN USER CODE
		HuaweiHelper.printConfig(config);
		
		List<IMendixObject> result = new ArrayList<IMendixObject>();
		ObsClient client = HuaweiHelper.GetStsClient(config);
		ListBucketsRequest request = new ListBucketsRequest();
		request.setQueryLocation(true);
		
		List<ObsBucket> buckets = client.listBuckets(request);
		
		buckets.forEach(bucket -> {
			Bucket mxBucket = new Bucket(getContext());
			mxBucket.setName(bucket.getBucketName());
			mxBucket.setCreationDate(bucket.getCreationDate());
			result.add(mxBucket.getMendixObject());
		});
		
//		client.close();
		return result;		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListBuckets";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
