// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazons3connector.proxies;

public class PutObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject putObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonS3Connector.PutObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		PutObject_Explorer("AmazonS3Connector.PutObject_Explorer"),
		PutObject_ExplorerDocument("AmazonS3Connector.PutObject_ExplorerDocument");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PutObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AmazonS3Connector.PutObject"));
	}

	protected PutObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject putObjectMendixObject)
	{
		if (putObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AmazonS3Connector.PutObject", putObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AmazonS3Connector.PutObject");

		this.putObjectMendixObject = putObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PutObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amazons3connector.proxies.PutObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amazons3connector.proxies.PutObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amazons3connector.proxies.PutObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazons3connector.proxies.PutObject(context, mendixObject);
	}

	public static amazons3connector.proxies.PutObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazons3connector.proxies.PutObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of PutObject_Explorer
	 */
	public final amazons3connector.proxies.Explorer getPutObject_Explorer() throws com.mendix.core.CoreException
	{
		return getPutObject_Explorer(getContext());
	}

	/**
	 * @param context
	 * @return value of PutObject_Explorer
	 */
	public final amazons3connector.proxies.Explorer getPutObject_Explorer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazons3connector.proxies.Explorer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PutObject_Explorer.toString());
		if (identifier != null)
			result = amazons3connector.proxies.Explorer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PutObject_Explorer
	 * @param putobject_explorer
	 */
	public final void setPutObject_Explorer(amazons3connector.proxies.Explorer putobject_explorer)
	{
		setPutObject_Explorer(getContext(), putobject_explorer);
	}

	/**
	 * Set value of PutObject_Explorer
	 * @param context
	 * @param putobject_explorer
	 */
	public final void setPutObject_Explorer(com.mendix.systemwideinterfaces.core.IContext context, amazons3connector.proxies.Explorer putobject_explorer)
	{
		if (putobject_explorer == null)
			getMendixObject().setValue(context, MemberNames.PutObject_Explorer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PutObject_Explorer.toString(), putobject_explorer.getMendixObject().getId());
	}

	/**
	 * @return value of PutObject_ExplorerDocument
	 */
	public final amazons3connector.proxies.ExplorerDocument getPutObject_ExplorerDocument() throws com.mendix.core.CoreException
	{
		return getPutObject_ExplorerDocument(getContext());
	}

	/**
	 * @param context
	 * @return value of PutObject_ExplorerDocument
	 */
	public final amazons3connector.proxies.ExplorerDocument getPutObject_ExplorerDocument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazons3connector.proxies.ExplorerDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PutObject_ExplorerDocument.toString());
		if (identifier != null)
			result = amazons3connector.proxies.ExplorerDocument.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PutObject_ExplorerDocument
	 * @param putobject_explorerdocument
	 */
	public final void setPutObject_ExplorerDocument(amazons3connector.proxies.ExplorerDocument putobject_explorerdocument)
	{
		setPutObject_ExplorerDocument(getContext(), putobject_explorerdocument);
	}

	/**
	 * Set value of PutObject_ExplorerDocument
	 * @param context
	 * @param putobject_explorerdocument
	 */
	public final void setPutObject_ExplorerDocument(com.mendix.systemwideinterfaces.core.IContext context, amazons3connector.proxies.ExplorerDocument putobject_explorerdocument)
	{
		if (putobject_explorerdocument == null)
			getMendixObject().setValue(context, MemberNames.PutObject_ExplorerDocument.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PutObject_ExplorerDocument.toString(), putobject_explorerdocument.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return putObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazons3connector.proxies.PutObject that = (amazons3connector.proxies.PutObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AmazonS3Connector.PutObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
