// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package huaweiobsconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.obs.services.ObsClient;
import com.obs.services.model.DeleteObjectRequest;
import huaweiobsconnector.HuaweiHelper;

public class DeleteObject extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __config;
	private huaweiobsconnector.proxies.HuaweiConfig config;
	private java.lang.String bucket;
	private java.lang.String key;

	public DeleteObject(IContext context, IMendixObject config, java.lang.String bucket, java.lang.String key)
	{
		super(context);
		this.__config = config;
		this.bucket = bucket;
		this.key = key;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.config = __config == null ? null : huaweiobsconnector.proxies.HuaweiConfig.initialize(getContext(), __config);

		// BEGIN USER CODE
		HuaweiHelper.printConfig(config);
		
		ObsClient client = HuaweiHelper.GetStsClient(config);
		DeleteObjectRequest req = new DeleteObjectRequest(this.bucket, this.key);
		client.deleteObject(req);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeleteObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
