// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package huaweiobsconnector.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.obs.services.ObsClient;
import com.obs.services.model.ListObjectsRequest;
import com.obs.services.model.ObjectListing;
import huaweiobsconnector.HuaweiHelper;

public class ListObjects extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __config;
	private huaweiobsconnector.proxies.HuaweiConfig config;
	private java.lang.String bucket;
	private java.lang.String prefix;
	private java.lang.Long maxObjects;

	public ListObjects(IContext context, IMendixObject config, java.lang.String bucket, java.lang.String prefix, java.lang.Long maxObjects)
	{
		super(context);
		this.__config = config;
		this.bucket = bucket;
		this.prefix = prefix;
		this.maxObjects = maxObjects;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.config = __config == null ? null : huaweiobsconnector.proxies.HuaweiConfig.initialize(getContext(), __config);

		// BEGIN USER CODE
		HuaweiHelper.printConfig(config);
		
		ObsClient client = HuaweiHelper.GetStsClient(config);
		List<IMendixObject> mxObjects = new ArrayList<IMendixObject>();
		
		ListObjectsRequest request = new ListObjectsRequest(this.bucket);
		request.setMaxKeys(this.maxObjects.intValue());
		// Set folder isolators to slashes.
		request.setDelimiter(this.prefix);
		
		ObjectListing objectListing;
		
		do {
			objectListing = client.listObjects(request);
			objectListing.getObjects().forEach(obj -> {
				HuaweiHelper.LOGGER.trace(String.format("ObsObject:: Bucket: %s, Object key: %s, Size: %s"
						, this.bucket
						, obj.getObjectKey()
						, obj.getMetadata().getContentLength()));
				
				mxObjects.add(HuaweiHelper.getMxObsObject(getContext(), obj, this.bucket).getMendixObject());
			});
		} while (objectListing.isTruncated());
		
		return mxObjects;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListObjects";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
