// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package huaweiobsconnector.proxies;

public enum AccessControlList
{
	REST_CANNED_PRIVATE(new java.lang.String[][] { new java.lang.String[] { "en_US", "REST_CANNED_PRIVATE" } }),
	REST_CANNED_PUBLIC_READ(new java.lang.String[][] { new java.lang.String[] { "en_US", "REST_CANNED_PUBLIC_READ" } }),
	REST_CANNED_PUBLIC_READ_WRITE(new java.lang.String[][] { new java.lang.String[] { "en_US", "REST_CANNED_PUBLIC_READ_WRITE" } }),
	REST_CANNED_PUBLIC_READ_DELIVERED(new java.lang.String[][] { new java.lang.String[] { "en_US", "REST_CANNED_PUBLIC_READ_DELIVERED" } }),
	REST_CANNED_PUBLIC_READ_WRITE_DELIVERED(new java.lang.String[][] { new java.lang.String[] { "en_US", "REST_CANNED_PUBLIC_READ_WRITE_DELIVERED" } }),
	REST_CANNED_AUTHENTICATED_READ(new java.lang.String[][] { new java.lang.String[] { "en_US", "REST_CANNED_AUTHENTICATED_READ" } }),
	REST_CANNED_BUCKET_OWNER_READ(new java.lang.String[][] { new java.lang.String[] { "en_US", "REST_CANNED_BUCKET_OWNER_READ" } }),
	REST_CANNED_BUCKET_OWNER_FULL_CONTROL(new java.lang.String[][] { new java.lang.String[] { "en_US", "REST_CANNED_BUCKET_OWNER_FULL_CONTROL" } }),
	REST_CANNED_LOG_DELIVERY_WRITE(new java.lang.String[][] { new java.lang.String[] { "en_US", "REST_CANNED_LOG_DELIVERY_WRITE" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private AccessControlList(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
