// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import java.util.LinkedList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazons3connector.AmazonHelper;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.ListObjectsRequest;
import software.amazon.awssdk.services.s3.model.ListObjectsResponse;

public class ListObjects extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __awsConfig;
	private amazons3connector.proxies.AwsConfig awsConfig;
	private java.lang.String bucket;
	private java.lang.String prefix;
	private java.lang.Long maxObjects;

	public ListObjects(IContext context, IMendixObject awsConfig, java.lang.String bucket, java.lang.String prefix, java.lang.Long maxObjects)
	{
		super(context);
		this.__awsConfig = awsConfig;
		this.bucket = bucket;
		this.prefix = prefix;
		this.maxObjects = maxObjects;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.awsConfig = __awsConfig == null ? null : amazons3connector.proxies.AwsConfig.initialize(getContext(), __awsConfig);

		// BEGIN USER CODE
		S3Client client = AmazonHelper.GetS3Client(awsConfig);
		ListObjectsRequest req = 
				ListObjectsRequest.builder().bucket(bucket).prefix(prefix).build();

		List<IMendixObject> result = new LinkedList<>();
		ListObjectsResponse res = client.listObjects(req);
		for (software.amazon.awssdk.services.s3.model.S3Object obj : res.contents()) {
			result.add(AmazonHelper.getMxS3Object(
					getContext(), obj, bucket).getMendixObject());
		}
		if (res.isTruncated()) {
			AmazonHelper.LOGGER.error("List has been truncated!");
		}
		
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListObjects";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
