// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazons3connector.AmazonHelper;
import amazons3connector.proxies.Prefix;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.ListObjectsV2Request;
import software.amazon.awssdk.services.s3.model.ListObjectsV2Response;
import software.amazon.awssdk.services.s3.model.S3Object;

public class ListPrefixes extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __awsConfig;
	private amazons3connector.proxies.AwsConfig awsConfig;
	private java.lang.String bucket;

	public ListPrefixes(IContext context, IMendixObject awsConfig, java.lang.String bucket)
	{
		super(context);
		this.__awsConfig = awsConfig;
		this.bucket = bucket;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.awsConfig = __awsConfig == null ? null : amazons3connector.proxies.AwsConfig.initialize(getContext(), __awsConfig);

		// BEGIN USER CODE
		S3Client client = AmazonHelper.GetS3Client(awsConfig);
		Set<String> prefixes = new HashSet<>();
		prefixes.add("");
		String continuationToken = null;
		
		while (true) {
			ListObjectsV2Request req = ListObjectsV2Request.builder()
					.continuationToken(continuationToken)
					.maxKeys(1000)
					.bucket(bucket)
					.build();
			ListObjectsV2Response res = client.listObjectsV2(req);
			
			for (S3Object obj : res.contents()) {
				String key = obj.key();
				if (key.endsWith("/")) {
					prefixes.add(key);
				}
			}
			
			if ((continuationToken = res.nextContinuationToken()) == null) {
				break;
			}
		}
		
		List<IMendixObject> result = new LinkedList<>();
		for (String prefix : prefixes) {
			Prefix mxPrefix = new Prefix(getContext());
			mxPrefix.setPrefix(prefix);
			result.add(mxPrefix.getMendixObject());
		}
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListPrefixes";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
