// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazons3connector.proxies;

/**
 * Represents the file metadata as stored in S3
 */
public class S3Object
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject s3ObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonS3Connector.S3Object";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		Bucket("Bucket"),
		Size("Size"),
		StorageClass("StorageClass"),
		LastChanged("LastChanged"),
		S3Object_Explorer("AmazonS3Connector.S3Object_Explorer");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public S3Object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AmazonS3Connector.S3Object"));
	}

	protected S3Object(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject s3ObjectMendixObject)
	{
		if (s3ObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AmazonS3Connector.S3Object", s3ObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AmazonS3Connector.S3Object");

		this.s3ObjectMendixObject = s3ObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'S3Object.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amazons3connector.proxies.S3Object initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amazons3connector.proxies.S3Object.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amazons3connector.proxies.S3Object initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazons3connector.proxies.S3Object(context, mendixObject);
	}

	public static amazons3connector.proxies.S3Object load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazons3connector.proxies.S3Object.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of Bucket
	 */
	public final java.lang.String getBucket()
	{
		return getBucket(getContext());
	}

	/**
	 * @param context
	 * @return value of Bucket
	 */
	public final java.lang.String getBucket(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Bucket.toString());
	}

	/**
	 * Set value of Bucket
	 * @param bucket
	 */
	public final void setBucket(java.lang.String bucket)
	{
		setBucket(getContext(), bucket);
	}

	/**
	 * Set value of Bucket
	 * @param context
	 * @param bucket
	 */
	public final void setBucket(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bucket)
	{
		getMendixObject().setValue(context, MemberNames.Bucket.toString(), bucket);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.Long getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.Long getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.Long size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of StorageClass
	 */
	public final java.lang.String getStorageClass()
	{
		return getStorageClass(getContext());
	}

	/**
	 * @param context
	 * @return value of StorageClass
	 */
	public final java.lang.String getStorageClass(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StorageClass.toString());
	}

	/**
	 * Set value of StorageClass
	 * @param storageclass
	 */
	public final void setStorageClass(java.lang.String storageclass)
	{
		setStorageClass(getContext(), storageclass);
	}

	/**
	 * Set value of StorageClass
	 * @param context
	 * @param storageclass
	 */
	public final void setStorageClass(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String storageclass)
	{
		getMendixObject().setValue(context, MemberNames.StorageClass.toString(), storageclass);
	}

	/**
	 * @return value of LastChanged
	 */
	public final java.util.Date getLastChanged()
	{
		return getLastChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of LastChanged
	 */
	public final java.util.Date getLastChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastChanged.toString());
	}

	/**
	 * Set value of LastChanged
	 * @param lastchanged
	 */
	public final void setLastChanged(java.util.Date lastchanged)
	{
		setLastChanged(getContext(), lastchanged);
	}

	/**
	 * Set value of LastChanged
	 * @param context
	 * @param lastchanged
	 */
	public final void setLastChanged(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastchanged)
	{
		getMendixObject().setValue(context, MemberNames.LastChanged.toString(), lastchanged);
	}

	/**
	 * @return value of S3Object_Explorer
	 */
	public final amazons3connector.proxies.Explorer getS3Object_Explorer() throws com.mendix.core.CoreException
	{
		return getS3Object_Explorer(getContext());
	}

	/**
	 * @param context
	 * @return value of S3Object_Explorer
	 */
	public final amazons3connector.proxies.Explorer getS3Object_Explorer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazons3connector.proxies.Explorer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.S3Object_Explorer.toString());
		if (identifier != null)
			result = amazons3connector.proxies.Explorer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of S3Object_Explorer
	 * @param s3object_explorer
	 */
	public final void setS3Object_Explorer(amazons3connector.proxies.Explorer s3object_explorer)
	{
		setS3Object_Explorer(getContext(), s3object_explorer);
	}

	/**
	 * Set value of S3Object_Explorer
	 * @param context
	 * @param s3object_explorer
	 */
	public final void setS3Object_Explorer(com.mendix.systemwideinterfaces.core.IContext context, amazons3connector.proxies.Explorer s3object_explorer)
	{
		if (s3object_explorer == null)
			getMendixObject().setValue(context, MemberNames.S3Object_Explorer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.S3Object_Explorer.toString(), s3object_explorer.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return s3ObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazons3connector.proxies.S3Object that = (amazons3connector.proxies.S3Object) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AmazonS3Connector.S3Object";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
